addons:
  apt:
    packages:
      - libva-dev
install:
  - pip install --user mako
language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
notifications:
  webhooks: http://build.servo.org:54856/travis
