addons:
  apt:
    packages:
      - libva-dev
env:
  - LLVM_VERSION=3.8
before_install:
  - ./before_install.sh
install:
  - pip install --user mako
language: rust
rust:
  - stable
cache: cargo
notifications:
  webhooks: http://build.servo.org:54856/travis
